package blue.endless.enoki.markdown.styles.properties;

import org.jetbrains.annotations.NotNull;

public class FloatStyleProperty extends StyleProperty<@NotNull Float> {
	private final float lowerBoundInclusive;
	private final float upperBoundInclusive;
	
	private FloatStyleProperty(String name, float lowerBoundInclusive, float upperBoundInclusive) {
		super(Float.class, name);
		
		this.lowerBoundInclusive = lowerBoundInclusive;
		this.upperBoundInclusive = upperBoundInclusive;
	}
	
	public static FloatStyleProperty of(String name, float lowerBoundInclusive, float upperBoundInclusive) {
		return new FloatStyleProperty(name, lowerBoundInclusive, upperBoundInclusive);
	}

	public static FloatStyleProperty of(String name) {
		return FloatStyleProperty.of(name, Float.NEGATIVE_INFINITY, Float.POSITIVE_INFINITY);
	}

	public static FloatStyleProperty nonNegativeOnly(String name) {
		return FloatStyleProperty.of(name, 0, Float.MAX_VALUE);
	}
	
	public static FloatStyleProperty positiveOnly(String name) {
		float lowerBound = Float.MIN_VALUE; // Check the JavaDocs on Float.MIN_VALUE!
		
		return FloatStyleProperty.of(name, lowerBound, Float.MAX_VALUE);
	}

	@Override
	public boolean isValid(@NotNull Float value) {
		return lowerBoundInclusive <= value && value <= upperBoundInclusive;
	}

	@Override
	public final boolean equals(Object object) {
		// This method is auto-generated by IntelliJ.
		
		if (!(object instanceof FloatStyleProperty that)) return false;
		if (!super.equals(object)) return false;

		return Float.compare(lowerBoundInclusive, that.lowerBoundInclusive) == 0
			&& Float.compare(upperBoundInclusive, that.upperBoundInclusive) == 0;
	}

	@Override
	public int hashCode() {
		// This method is auto-generated by IntelliJ.
		
		int result = super.hashCode();
		result = 31 * result + Float.hashCode(lowerBoundInclusive);
		result = 31 * result + Float.hashCode(upperBoundInclusive);
		return result;
	}
}
